version: '3'

services:
  promtail:
    container_name: promtail
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - loki-data:/loki
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  loki:
    container_name: loki
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    image: grafana/loki:latest
    ports:
      - 9677:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=Europe/Moscow
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - 9688:3000
    networks:
      - loki

networks:
  loki:
volumes:
  loki-data:
