# Usage:
#     docker-compose run archivebox init --setup
#     docker-compose up
#     echo "https://example.com" | docker-compose run archivebox archivebox add
#     docker-compose run archivebox add --depth=1 https://example.com/some/feed.rss

version: '3.9'

services:
  archivebox:
    image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
    command: server --quick-init 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - ALLOWED_HOSTS=*
      - PUBLIC_INDEX=False
      - PUBLIC_SNAPSHOTS=False
      - SAVE_ARCHIVE_DOT_ORG=True
      - CHECK_SSL_VALIDITY=False
      - MEDIA_MAX_SIZE=750m

  ### Example: Put Nginx in front of the ArchiveBox server for SSL termination
  # nginx:
  #     image: nginx:alpine
  #     ports:
  #         - 443:443
  #         - 80:80
  #     volumes:
  #         - ./etc/nginx.conf:/etc/nginx/nginx.conf
  #         - ./data:/var/www
